- name: Install python packages
  ansible.builtin.pip:
    name:
      - kubernetes
- name: Update API
  ansible.builtin.include_tasks: api.yaml

- name: Update Ingress
  ansible.builtin.include_tasks: ingress.yaml

- name: Get current cluster context
  ansible.builtin.command: oc config current-context
  register: current_context
  changed_when: current_context.rc != 0

- name: Get current cluster name
  ansible.builtin.command: oc config view -o jsonpath='{.contexts[?(@.name == "{{ current_context.stdout }}")].context.cluster}'
  register: cluster_name
  changed_when: cluster_name.rc != 0

- name: Get current cluster API URL
  ansible.builtin.command: oc config view -o jsonpath='{.clusters[?(@.name == "{{ cluster_name.stdout }}")].cluster.server}'
  register: cluster_url
  changed_when: cluster_url.rc != 0

- name: Update host address # noqa: no-changed-when
  when: cluster_url.stdout != "https://api." + domain + ":6443"
  ansible.builtin.command: oc config set clusters.{{ cluster_name.stdout }}.server "{{ 'https://api.' + domain + ':6443' }}"
